"""Unique usernames

Revision ID: b45d26e9ed44
Revises: bf12b0a21146
Create Date: 2019-07-12 17:29:52.061977

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b45d26e9ed44'
down_revision = 'bf12b0a21146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as bop:
        bop.create_unique_constraint('user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
