"""changed password for password hash

Revision ID: bf12b0a21146
Revises: 3b69481a413f
Create Date: 2019-07-11 20:13:56.940587

"""
from alembic import op
import sqlalchemy as sa
from alayatodo.models import User
from alayatodo import db

# revision identifiers, used by Alembic.
revision = 'bf12b0a21146'
down_revision = '3b69481a413f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as bop:
        bop.alter_column('password', new_column_name='password_hash')
    users = User.query.all()
    for user in users:
        user.set_password(user.password_hash)
        db.session.add(user)
    db.session.commit()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password_hash', new_column_name='password')
    # ### end Alembic commands ###
